### ISSUE TITLE
13.x 闪退

### ISSUE THREAD

**Issue by Demonsword27** [youngsoft/YSBlockHook#4]
原因是invoke替换时发生崩溃，原因不知。可能是内部做了保护

**Comment by CrazyZombies** [comment]
> 原因是invoke替换时发生崩溃，原因不知。可能是内部做了保护

请问这个问题解决了吗？我也遇到了。iOS 14.x 也是 crash

**Comment by Demonsword27** [comment]
@CrazyZombies 原因是因为ios13之后，系统修改了globeblock的执行权限，变成了只读权限，具体看我的主页，bqblockhook

**Comment by CrazyZombies** [comment]
> @CrazyZombies 原因是因为ios13之后，系统修改了globeblock的执行权限，变成了只读权限，具体看我的主页，bqblockhook

赞，我去瞧瞧

**Comment by CrazyZombies** [comment]
> @CrazyZombies 原因是因为ios13之后，系统修改了globeblock的执行权限，变成了只读权限，具体看我的主页，bqblockhook

老哥方便加个微信交流下吗

**Comment by Demonsword27** [comment]
@Wbqqqq 18815276479
